project_id = "vivfrsrgknzhxgbcvzte"

[functions.process-sales-upload]
verify_jwt = false

[functions.evaluate-medals]
verify_jwt = false

[functions.calcular-sp-semanal]
verify_jwt = false

[functions.sync-databricks]
verify_jwt = false
