project_id = "vivfrsrgknzhxgbcvzte"

[functions.process-sales-upload]
verify_jwt = false

[functions.evaluate-medals]
verify_jwt = false

[functions.calcular-sp-semanal]
verify_jwt = false

[functions.sync-databricks]
verify_jwt = false

[functions.validar-cruce-asesores]
verify_jwt = false

[functions.validar-consistencia-familias]
verify_jwt = false

[functions.evaluar-retos-vc]
verify_jwt = false

[functions.sync-metas-historicas]
verify_jwt = false

[functions.fix-account-access]
verify_jwt = false
