// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my Siigo Arena profile",
  description: "Returns the signed-in user's Siigo Arena profile: name, email, country, channel, cell, leader, SP Convenci\xF3n and SP Canje totals.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("gerentes").select(
      "id, nombre, email, pais, canal, celula, lider, familia_vc, sp_convencion, sp_canje, activo"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No Siigo Arena profile linked to this account." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-my-sp-history.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_sp_history_default = defineTool2({
  name: "get_my_sp_history",
  title: "Get my Siigo Points history",
  description: "Returns the signed-in user's Siigo Points entries (sp_acumulados) grouped by period, with type (convencion/canje) and source. Optionally filter by period (YYYYMM) or tipo_sp.",
  inputSchema: {
    periodo: z.string().regex(/^\d{6}$/).optional().describe("Period in YYYYMM format (e.g. 202606). Optional."),
    tipo_sp: z.enum(["convencion", "canje"]).optional().describe("Filter by SP type. Optional."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ periodo, tipo_sp, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data: gerente, error: gErr } = await sb.from("gerentes").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (gErr || !gerente) {
      return { content: [{ type: "text", text: "No profile linked." }], isError: true };
    }
    let q = sb.from("sp_acumulados").select("periodo, tipo_sp, sp, fuente, detalle, created_at").eq("gerente_id", gerente.id).order("periodo", { ascending: false }).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (periodo) q = q.eq("periodo", periodo);
    if (tipo_sp) q = q.eq("tipo_sp", tipo_sp);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-ranking.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_ranking_default = defineTool3({
  name: "get_ranking",
  title: "Get Siigo Arena ranking",
  description: "Returns the top managers ranking for a channel and country in Siigo Arena. Use segment='vc' for Venta Cruzada or 'vn' for Venta Nueva.",
  inputSchema: {
    segment: z2.enum(["vc", "vn"]).describe("Ranking segment: 'vc' (Venta Cruzada) or 'vn' (Venta Nueva)."),
    pais: z2.enum(["COL", "MEX", "ECU", "URU"]).describe("Country code."),
    mes: z2.string().regex(/^\d{6}$/).optional().describe("Month in YYYYMM. Defaults to the latest available."),
    limit: z2.number().int().min(1).max(50).optional().describe("Top N rows (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ segment, pais, mes, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const table = segment === "vc" ? "ranking_vc_gerentes" : "ranking_vn_gerentes";
    const monthCol = segment === "vc" ? "mes" : "mes_periodo";
    let targetMes = mes;
    if (!targetMes) {
      const { data: latest } = await sb.from(table).select(monthCol).eq("pais", pais).order(monthCol, { ascending: false }).limit(1);
      targetMes = latest?.[0]?.[monthCol] ?? void 0;
    }
    if (!targetMes) {
      return { content: [{ type: "text", text: "No ranking data available." }], isError: true };
    }
    const { data, error } = await sb.from(table).select("*").eq("pais", pais).eq(monthCol, targetMes).order("posicion", { ascending: true }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ mes: targetMes, ranking: data }) }],
      structuredContent: { mes: targetMes, ranking: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-rewards.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_rewards_default = defineTool4({
  name: "list_rewards",
  title: "List available rewards",
  description: "Returns the active rewards (premios) catalog available to redeem with SP Canje. Optionally filter by country and operation.",
  inputSchema: {
    pais: z3.enum(["COL", "MEX", "ECU", "URU"]).optional().describe("Country code filter."),
    operacion: z3.string().optional().describe("Operation filter (e.g. 'Venta Cruzada').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pais, operacion }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("premios").select("id, nombre, descripcion, costo_puntos, stock, pais, operacion, imagen_url").eq("activo", true).order("costo_puntos", { ascending: true });
    if (pais) q = q.eq("pais", pais);
    if (operacion) q = q.eq("operacion", operacion);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { rewards: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vivfrsrgknzhxgbcvzte";
var mcp_default = defineMcp({
  name: "siigo-arena-mcp",
  title: "Siigo Arena",
  version: "0.1.0",
  instructions: "Tools for Siigo Arena, the gamification platform for Siigo's commercial teams (Venta Cruzada and Venta Nueva across COL, MEX, ECU, URU). Use `get_my_profile` for the signed-in user's SP totals, country and channel. Use `get_my_sp_history` for their SP Convenci\xF3n / SP Canje entries per period (YYYYMM). Use `get_ranking` for the top managers ranking by segment (vc/vn) and country. Use `list_rewards` to browse the SP Canje rewards catalog.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_my_sp_history_default, get_ranking_default, list_rewards_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
